### ISSUE TITLE
Release new version to support redix 0.7

### ISSUE THREAD

**Issue by tompave** [whatyouhide/redix_pubsub#16]
Currently `redix_pubsub 0.4.2` requires `redix ~> 0.6.0`.
I've tried it in a project with `redix 0.7.0`, and everything seems to work fine.

Is it possible to release a new version to turn `~> 0.6.0` into `~> 0.6`?

Thanks!

**Comment by tompave** [comment]
hi @whatyouhide, have you had a chance to see this?

**Comment by CaldwellYSR** [comment]
I also have this issue and would be interested in an update.

**Comment by scouten** [comment]
Any chance we could get you to reconsider #17 as a temporary measure until the expected rework of Redix is complete?

**Comment by whatyouhide** [comment]
Released v0.5.0 which requires Redix v0.8.0, so this can be closed.
