### ISSUE TITLE
New add-on for Fastlane.

### ISSUE THREAD

**Issue by merqlove** [whatyouhide/redix_pubsub#2]
Hi, thanks for your work!

Just realized Fastlane pattern(currently in active testing), based on Redix.PubSub
https://github.com/merqlove/redix_pubsub_fastlane

**Comment by merqlove** [comment]
@whatyouhide As i see casts is always better for fast respond. Too plans to change all my calls into it. Otherwise page loading can be slow...

**Comment by merqlove** [comment]
Yeah, its is. Converted & added monitors for GC. Now it works good :)

**Comment by whatyouhide** [comment]
Hey @merqlove, I'm glad you found redix_pubsub useful :) However, I can't see the point of this issue (other than notifying me?) and so I'm gonna go ahead and close it. Feel free to open issues for bugs or possible questions :) 💟
