### ISSUE TITLE
Release a 0.4.x version to support redix 0.7

### ISSUE THREAD

**Issue by tompave** [whatyouhide/redix_pubsub#20]
Hi,

I'm reopening https://github.com/whatyouhide/redix_pubsub/issues/16 because I need to rely on `redix 0.7`.

I maintain a library that needs to support Elixir `1.4` and `1.5`, and [`redix 0.8` drops support for Elixir `< 1.6`](https://github.com/whatyouhide/redix/blob/master/CHANGELOG.md#v080). That was a bit unexpected, because `redix 0.7` drops support for Elixir `< 1.3`, and I wonder what happened to Elixir `1.4` and `1.5`: have they just been skipped?

As the original issue (https://github.com/whatyouhide/redix_pubsub/issues/16) explains, I was locked to `redix 0.6` and `redis_pubsub 0.4.2` because of their hard dependency. Since I can't just upgrade to `redix 0.8`, I can't use this `redix_pubsub` update either.

Would it be possible to release a version so that I can upgrade to `redix 0.7`?

**Comment by whatyouhide** [comment]
@tompave why do you need Redix 0.7? The changelog for that version is very very small. Maybe we can find an easier fix for this.

**Comment by tompave** [comment]
Hi, thanks for the quick reply.

I'd be happy to update to `redix 0.8` if I could, but I need to support Elixir `1.4` and `1.5` (although I could drop `1.4`), and `redix 0.8` drops support for Elixir `< 1.6`.

**Comment by whatyouhide** [comment]
@tompave yep, I got that. What I'm asking is why you can't use Redix **0.7**, which supports 1.4 and on. The reason I dropped 1.4 and 1.5 altogether is so that I could use `gen_statem`.

**Comment by tompave** [comment]
Oh, right.

I can't use `redix` 0.7 because I need to also use `redix_pubsub`, and there is no compatible version.

* `redix_pubsub 0.4.2` depends on `redix ~> 0.6.0`, so I can't upgrade above `redix 0.6.1`.
* `redix_pubsub 0.5.0` depends on `redix ~> 0.8`, so I can't juse use `redix 0.7`.

And I can't just upgrade to `redix 0.8` because it requires Elixir `1.6`, and I need to support `1.5`.

**Comment by tompave** [comment]
That's why I'm asking to release a `redix_pubsub 0.4.3` that relaxes the `redix` version.

**Comment by whatyouhide** [comment]
Sorry, I wrote one thing in my original reply and another one in the next comment. The original question was: why do you need 0.7? What features/fixes does it have that you need?

**Comment by tompave** [comment]
> The original question was: why do you need 0.7? What features/fixes does it have that you need?

My original response still applies :-)

> I'd be happy to update to redix 0.8 if I could, but I need to support Elixir 1.4 and 1.5 (although I could drop 1.4), and redix 0.8 drops support for Elixir < 1.6.

**Comment by whatyouhide** [comment]
Yes I understand why you can't upgrade to 0.7 or 0.8. My question is: why do you need to upgrade?

**Comment by tompave** [comment]
> I understand why you can't upgrade to 0.7 or 0.8.

I can upgrade to 0.7. It's just 0.8 that I can't use.

> My question is: why do you need to upgrade?

Oh, you're asking why I can't just stay on Redix 0.6.1 and Redix.PubSub 0.4.2?

Well, I could, but they're old versions. The problem is that any application that is using my library would also be forced to use those old versions, even though they might want to use a more recent one.

In the end, this is just to avoid version conflicts in the user applications.

**Comment by whatyouhide** [comment]
I understand but the difference from 0.6 to 0.7 is basically just dropping support for Elixir 1.4, so I don't really expect users to *need* 0.7 over 0.6. So your library will be forced to stay on 0.6 until it decides to drop support for Elixir < 1.6. Note that if you were able to upgrade to 0.7, you'd have the exact same problem since the latest Redix version is 0.8.

**Comment by tompave** [comment]
Ok, thanks. I guess I'll have to drop the old Elixir versions of I want to upgrade.

**Comment by whatyouhide** [comment]
Yep. I usually try really hard to keep Elixir compatibility if possible, but this time I could drop dependencies and rewrite Redix with a more robust, `gen_statem`-based solution if I dropped Elixir 1.6. It might be uncomfortable now but it will only get better as 1.6 gets older :)
