### ISSUE TITLE
UNSUBSCRIBE: ArgumentError :erlang.port_command, :gen_tcp.send

### ISSUE THREAD

**Issue by merqlove** [whatyouhide/redix_pubsub#5]
Found some raise in the same perspective.
[lib/redix/pubsub/connection.ex#L328](https://github.com/whatyouhide/redix_pubsub/blob/master/lib/redix/pubsub/connection.ex#L328)

```
00:30:40.692 [error] Process #PID<0.364.0> raised an exception
** (ArgumentError) argument error
    :erlang.port_command(#Port<0.6577>, [42, "2", "\r\n", [[36, "11", "\r\n", "UNSUBSCRIBE", "\r\n"], [36, "3", "\r\n", "ccc", "\r\n"]]], [])
    :prim_inet.send/3
    (redix_pubsub) lib/redix/pubsub/connection.ex:328: Redix.PubSub.Connection.send_noreply_or_disconnect/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by whatyouhide** [comment]
No idea why this is happening, do you have steps to reproduce this?

**Comment by merqlove** [comment]
I've seen this error once, only in tests.
Really hard to reproduce...
I will add some logs/info about, if it will be arrived again...

**Comment by whatyouhide** [comment]
@merqlove awesome, let me know if I can help. I can investigate tomorrow likely :)

**Comment by whatyouhide** [comment]
Hey, sorry, haven't had a change to investigate yet. Do you have any news on your side? :)

**Comment by merqlove** [comment]
@whatyouhide heya, no, i'm was on ruby side for a week :) but anyway i haven't seen this error in production logs, only within specs. 
I plan to work on Elixir project with integrated PubSub on this week. So we can close current thread until it fires again:)
 also had questions to you about PubSub specific, i will wrote into slack :))

**Comment by whatyouhide** [comment]
@merqlove that sounds like a great plan, ping me anytime. I will leave this open however, no worries, just let me know if you manage to reproduce this :)

**Comment by whatyouhide** [comment]
Ping @merqlove? :)

**Comment by merqlove** [comment]
Hi Andrea, i think it can be closed. Problem didn't appear again all this time 👍

**Comment by whatyouhide** [comment]
Awesome :) If anyone experiences this again, feel free to ping here and we will reopen. Thanks a lot @merqlove! 💟

**Comment by merqlove** [comment]
Sure, thanks for nice modules! :1st_place_medal: 💎 💎 💎
