### ISSUE TITLE
Not receiving a message

### ISSUE THREAD

**Issue by holgeradam** [whatyouhide/redix_pubsub#9]
Hi there,

I have a weird issue with pub/sub. The channel subscription works as expected, but after that no message can be received using this package.
The setup is a redis docker container running on MacOs. Elixir is up to date.
I set up a sample project requiring redix_pubsub 0.2.0, then started iex -S mix. Then this:

iex(1)> {:ok, pubsub} = Redix.PubSub.start_link()
{:ok, #PID<0.164.0>}
iex(2)> Redix.PubSub.subscribe(pubsub, "my_channel", self())
:ok
iex(3)> flush()
{:redix_pubsub, #PID<0.164.0>, :subscribed, %{channel: "my_channel"}}
:ok
// So far, so good. The subscription worked.
iex(4)> flush()
:ok
// At this point the redis message was published via redis-cli, see below. It is never received here.
iex(5)>

I published the message after the successful subscription using redis-cli like this:
127.0.0.1:6379> PUBLISH my_channel hello
(integer) 1

redis-cli monitor tells me this, verifying that the message is not going through:
1490714652.425079 [0 172.24.0.1:50936] "SUBSCRIBE" "my_channel"
1490714667.394015 [0 172.24.0.1:50938] "COMMAND"
1490714668.348758 [0 172.24.0.1:50938] "PUBLISH" "my_channel" "hello"

Tested the same procedure on Ubuntu and it worked as expected, so I am assuming it is a problem on my machine.
However... 
- Receiving messages in general (redis-cli SUBSCRIBE for example) works as expected.
- :redix publishing works fine.
- Receiving the message in Elixir using :exredis works as well (huh?).

I assume I can rule out a connection problem between the redis container and Elixir/BEAM, otherwise :exredis wouldn't work and the subscription shouldn't be successful.

Other than that I am out of ideas. Any hints would be greatly appreciated. :)

**Comment by holgeradam** [comment]
I just confirmed this with another Mac running 10.12 (same as mine), the same thing happens. Seems to be related to the OS. :/

**Comment by tompave** [comment]
Hi, which versions of `redix` and `redix_pubsub` are you using? Are you using the same version on both macOS and Ubuntu?

You can try to have a look at this PR: https://github.com/whatyouhide/redix_pubsub/pull/8 (it links to another issue in the Redix repo with more details).

**Comment by holgeradam** [comment]
Hi,

I was using redix 0.5.0 and redix_pubsub 0.2.0 on all OS. I just updated to 0.3.0 and redix 0.5.2 and the issue is resolved. The messages are received now. Thanks for your help!

**Comment by whatyouhide** [comment]
Awesome, thanks for the report and sorry for the long wait @holgeradam  💟

**Comment by holgeradam** [comment]
You're welcome, thanks for the support. I'm glad this is resolved, because I love the package.  :)
